### ISSUE TITLE
Ability to warn instead of error

### ISSUE THREAD

**Issue by amk221** [rwjblue/ember-template-lint#337]
Example scenario:

I want to use `quotes: ['double']`, but our existing templates have a mixture of single and double quotes.

To add this rule now, would mean a big-bang fix PR.

I would like the ability to just receive a warning, and gradually move over. Much like eslint allows.

**Comment by rwjblue** [comment]
I actually dislike that technique of migrating to a more strict set of rules. 

I would suggest instead that you make your rules as strict as possible, then use `ember-cli-template-lint'`s `ember template-lint:print-failing` command to generate a list suitable for entering into the `pending` field in your `.template-lintrc.js`.

Specifically, this path:

* ensures that any new files you add _must_ conform to the strictest rule set
* files can be fixed individually (and subsequently removed from the pending list when they pass)
* no big bang PR required

**Comment by amk221** [comment]
Ah, fab thanks

**Comment by jacobq** [comment]
So there is no way to configure a rule so that it generates a warning instead of an error?

I like the sound of the process recommended above in general, but for a lonely team of one there is often little value to be gained from changing trivial things like where to break lines when writing component parameters. So if the tool is going to be so draconian that all I can do is turn a rule on or off I'm often going to have to forego most of the benefits of the linting and just turn it off. :( I want to conform to recommended guidelines, but unless there's some automatic fixing process there's no way I'll be able to justify to my employer that I spent a day or two reformatting code / configuring linter rules. Plus it is really annoying to realize after waiting 20min for a CI build that it balked because of a linter violation even though the code otherwise would build just fine and pass its test suite.
